# Generated by Django 5.2.6 on 2025-09-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_DB',
            fields=[
                ('Car_name', models.CharField(max_length=20)),
                ('Fuel_efficient', models.FloatField()),
                ('Color', models.CharField(max_length=10)),
                ('Prize', models.IntegerField()),
                ('CarID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
